In [14]:
import pandas as pd
import matplotlib as plt
import glob, os
import csv
import datetime

In [25]:
test = pd.read_csv("201904-capitalbikeshare-tripdata.csv")
bike06 =pd.read_csv("202006-capitalbikeshare-tripdata 2.csv")
test.head()

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,313,4/1/19 0:03,4/1/19 0:08,31618,4th & East Capitol St NE,31630,15th & East Capitol St NE,W24063,Member
1,453,4/1/19 0:07,4/1/19 0:15,31119,14th & Belmont St NW,31298,15th & M St NW,W22080,Member
2,333,4/1/19 0:09,4/1/19 0:15,31203,14th & Rhode Island Ave NW,31519,1st & O St NW,W00276,Member
3,568,4/1/19 0:10,4/1/19 0:19,31202,14th & R St NW,31103,16th & Harvard St NW,W21582,Member
4,1609,4/1/19 0:10,4/1/19 0:37,31517,Union Market,31655,New Jersey Ave & F St NW,75558,Member

In [26]:
test['Start date'] = pd.to_datetime(test['Start date'])
test['Start date'] = pd.to_datetime(test['End date'])
test['day_of_week'] = test['Start date'].dt.day_name()
print(test.sample(5))

        Duration          Start date       End date  Start station number  \
147899       830 2019-04-13 15:22:00  4/13/19 15:22                 31603
177005       885 2019-04-16 12:27:00  4/16/19 12:27                 31290
116368       386 2019-04-10 18:43:00  4/10/19 18:43                 31623
342158       373 2019-04-30 15:58:00  4/30/19 15:58                 31042
338562      1498 2019-04-30 09:03:00   4/30/19 9:03                 31405

                             Start station  End station number  \
147899                       1st & M St NE               31506
177005       17th St & Independence Ave SW               31249
116368     Columbus Circle / Union Station               31612
342158  Market Square / King St & Royal St               31043
338562         Georgia Ave & Emerson St NW               31266

                           End station Bike number Member type day_of_week
147899       1st & Rhode Island Ave NW      W01443      Member    Saturday
177005              Jefferson Memorial      W01033      Casual     Tuesday
116368          D St & Maryland Ave NE      W23769      Member   Wednesday
342158  Saint Asaph St & Pendleton  St      W23324      Member     Tuesday
338562                  11th & M St NW      W21569      Member     Tuesday

In [27]:
bike06.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,16A86B048B01DE6F,docked_bike,6/10/20 20:20,6/10/20 20:27,Edgewood Rec Center,642.0,Rhode Island Ave Metro,368.0,38.924144,-77.002098,38.920682,-76.995876,member
1,661EA082175DB7E9,docked_bike,6/23/20 6:31,6/23/20 6:58,Wisconsin Ave & O St NW,289.0,Edgewood Rec Center,642.0,38.908490,-77.063586,38.924144,-77.002098,member
2,15C659A06C439B74,docked_bike,6/6/20 11:49,6/6/20 11:49,19th & K St NW,269.0,19th & K St NW,269.0,38.902204,-77.043370,38.902204,-77.043370,member
3,59AD75CFBF96DEC1,docked_bike,6/6/20 11:52,6/6/20 12:21,19th & K St NW,269.0,10th & K St NW,199.0,38.902204,-77.043370,38.902400,-77.026220,member
4,06F6881BEFCFC106,docked_bike,6/7/20 15:25,6/7/20 17:15,37th & O St NW / Georgetown University,152.0,Georgetown Harbor / 30th St NW,102.0,38.907740,-77.071652,38.902221,-77.059219,casual

In [3]:
path = "/Users/germanportes/Documents/GW_Bootcamp/Project/Group-Project_team3/Resources"
path

'/Users/germanportes/Documents/GW_Bootcamp/Project/Group-Project_team3/Resources'

In [4]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
bikeshare= pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
bikeshare.to_csv( "Bikeshare_data.csv", index=False, encoding='utf-8')

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3254: DtypeWarning: Columns (1,2,4,6,7,8,9,10,11,12,13,15,21,22) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):